# This is a template for other packages (i.e., beside pfs_pipe2d) to use
# as a ".travis.yml" file to enable Travis-CI. This enables CI on the
# entire pipeline when changing only a single product in the stack.

language: minimal
services:
  - docker
os:
  - linux
jobs:
  fast_finish: true
notifications:
  email: false
  slack:
    secure: ya2Zm9a/oygq/POzSDd/ZDcztm5G8Z8EUvazAzqRdrZ14WLmzVdAmNsdtSeesfh949D6Ci12EQvGMo4mhR3JNB/a5xiXZ1G6vNcrj1glDttMRb0z9j9y4EwFZFIIfUljlSWgdXSXM/31HQD+IAnRg/1v5C+WcrwXcuGh1AhOOrOHHL7UT7IiitojCB8fccQavp7VH9OCV9Wv7TvBIGvfGJOINUAVK72j6nSlLyU79/XpdJEZhdq5+5ouwFiLAZHOOqXnc524JqMtgs6l0mFQ/m/609ufRlP4YDGn1f22dQDjpGpjWWGJnnP3TiYIofTKr2jKoUmwpPI+0FJg5Z/daTBIvBUogKISXMmRQvTskdzzf8fMLWkl8O/F5XJ0QAenT1Cw3dTjCCctH7lQdNoex2oYFU538Nm5q0FBbytJgcgGChWuIaTP95usaWwro8dtlY0DA4Yh+e0DsZBTB+UwxY9jdUlpB0ifFq/DmLmJ8dYHKO2YIizWPE7V1hNh1swsHqaPJDYHLEYnmyclwMQPB6YYVHsxfYRMW0mIrXHTZbCwmqduAAH26lxL3f5Z4QVoz+cGeAvMVWjGMBy4kKwMF1ANRD7hDrXTHYjhUGNqXBfIdzb4G/nhXvlVOUHWqVKiMnmf531tq3AC6w3VvIaN0FQi6aWB0pugbxxJ9KDE7Zc=
branches:
  only:
    - master

# The actual installation is done under the 'script' so as to consolidate the
# necessary front-end machinery (intercept log, decide which branch to use).
install:
  - cd $HOME
  - git clone -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --single-branch http://github.com/Subaru-PFS/pfs_pipe2d || git clone -b master --single-branch http://github.com/Subaru-PFS/pfs_pipe2d
script: /bin/bash pfs_pipe2d/bin/pfs_travis.sh
